# Jekyll GitHub Pages CI

name: Jekyll GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true  # Caches the gems to speed up build

    - name: Build the site
      run: |  
        bundle install
        bundle exec jekyll build

    - name: Test
      run: |  
        bundle exec jekyll build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Deploy
      run: |  
        echo "Deploying to GitHub Pages..."
